#!/usr/bin/env bash
set -e

FORMAT_FILES=$(
  git --no-pager diff --name-status --no-color --cached | \
    awk '$1 != "D" && $2 ~ /\.py$/ {print $NF}'
)

if [ -n "$FORMAT_FILES" ]; then
  black --quiet "$FORMAT_FILES"
  git add "$FORMAT_FILES"
fi
