#!/usr/bin/env bash
set -e

FORMAT_FILES=$(
  git --no-pager diff --name-status --no-color --cached | \
    awk '$1 != "D" && $2 ~ /\.exs?$/ {print $NF}'
)

mix format "$FORMAT_FILES"

git add "$FORMAT_FILES"
