#!/usr/bin/env bash
set -e

filesToFormat=$(
  git --no-pager diff --name-status --no-color --cached | \
    awk '$1 != "D" && $2 ~ /\.c|\.h/ {print $NF}'
)

for path in $filesToFormat
do
  clang-format -i "$path"
  git add "$path"
done;
