# frozen_string_literal: true

source "https://rubygems.org"

gem "jekyll", "~> 4.3.2"

# This is the default theme for new Jekyll sites. You may change this to anything you like.
gem "minima", "~> 2.5"

# If you have any plugins, put them here!
group :jekyll_plugins do
  gem "jekyll-feed", "~> 0.12"
end
