#!/usr/bin/env bash

# Exit immediately if the script encounters a non-zero status.
set -e

# If set, Bash includes filenames beginning with a `.` in the results of
# filename expansion. The filenames `.` and `..` must always be matched
# explicitly, even if dotglob is set.
shopt -s dotglob

# ============================================================
# PROLOGUE
# ============================================================

# Create a new top-level directory as fallback in case $BUILD (defined below)
# is ever empty.
mkdir -p "/tmp/bs.mix"

# Create an intermediate build directory. The final step of this script will
# copy the content from this directory to $OUT.
BUILD=$(mktemp -d -p "/tmp/bs.mix")

if [ -z "$BUILD" ]; then
  >&2 echo "Failed to create temp directory."
  exit 1
fi

# Deletes the intermediate build directory on exit. We use a concatenation of
# the intermediate directory with the basename of the generated temp directory
# to ensure we never evaluate to root (i.e. `/`). That should never actually
# happen but a good habit to establish nonetheless.
function cleanup {
  rm -r "/tmp/bs.mix/$(basename "$BUILD")"
}

trap cleanup EXIT

# ============================================================
# ENVIRONMENT
# ============================================================

if [ -z "$MODULE" ]; then
  MODULE_ARG=
else
  MODULE_ARG="--module '$MODULE'"
fi

# ============================================================
# BUILD
# ============================================================

# Copy template contents over to the intermediate build directory.
cp -r template/* "$BUILD"

# Explicitly set permissions on all copied files.
find "$BUILD" -type f -execdir chmod 644 {} +
find "$BUILD" -type d -execdir chmod 755 {} +
chmod 755 "$BUILD"/.githooks/pre-commit

# Generate a new project with the specified name using `mix`. Generate in a
# subdirectory to avoid interactive conflict resolution.
nix develop "$BUILD" \
  --command bash \
  -c "mix new $BUILD/bs.project --app '$APP' $MODULE_ARG"

# Copy the generated files into the intermediate build directory.
mv -f "$BUILD"/bs.project/* "$BUILD"
rmdir "$BUILD"/bs.project

# Overwrite the generated README in favor of that defined in our template.
cp template/README.md "$BUILD"
chmod 644 "$BUILD"/README.md

# ============================================================
# REWRITES
# ============================================================

# ix file. The mix generator would fail if $APP did not consist of just
# lowercase ASCII letters, numbers, or underscores. Thus $APP is safe to
# interpolate into the following command.
sed -i "s/<APP>/$APP/g" "$BUILD/flake.nix"

# ============================================================
# EPILOGUE
# ============================================================

# Success! Copy contents to target directory.
cp -r "$BUILD"/* "$OUT"
