#!/usr/bin/env bash
set -e

filesToFormat=$(
  git --no-pager diff --name-status --no-color --cached | \
    awk '$1 != "D" && $2 ~ /\.jsx?$|\.tsx?$/ {print $NF}'
)

for path in $filesToFormat
do
  prettier --write "$path"
  git add "$path"
done
